### ISSUE TITLE
Вариант задания.

### ISSUE THREAD

**Issue by aulianenko** [Andrew0701/coursework-web#1]
Выбираем тему курсового проекта.
p.s.: мне скучно :dancer:

**Comment by ghost** [comment]
какие последние варианты? на чем остановились?

**Comment by aulianenko** [comment]
Дизайнерская студия была, но от неё вроде отказались.

**Comment by ghost** [comment]
то есть надо самим придумать, а если уж ниче в голову не лезет, то выбрать из предложенных в методе. такой расклад?

**Comment by aulianenko** [comment]
Этот момент надо будет уточнить на собрании по практике.

**Comment by ghost** [comment]
Ты когда приезжаешь?

**Comment by aulianenko** [comment]
В четверг вечером скорее всего.

**Comment by ghost** [comment]
Веб делаешь?

**Comment by aulianenko** [comment]
Ещё не начинал.

**Comment by ghost** [comment]
Что ж, тему походу выбрали, флудить в скайп)
