### ISSUE TITLE
Using ES 6 features breaks compatibility with legacy browsers

### ISSUE THREAD

**Issue by alex-zuy** [Andrew0701/coursework-web#8]
Many ES 6 features are only available on recent versions of browsers or not available at all. Their usage must be judged. For example:
template strings(aka string interpolation) [use case](https://github.com/Andrew0701/coursework-web/blob/master/progress/home/static/home/js/reg.js#L21). Compatibility [matrix](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings#Browser_compatibility)

``` javascript
    $(`input[value=${formName}]`).change(function(){
        if ($(this).is(':checked')) {
            $(`form#${formName}`).show();
            $(`form#${otherForm}`).hide();
        }
    }
```

so this code will work neither in safari, nor in IE ;(

**Comment by ghost** [comment]
Какая версия Jquery?

**Comment by alex-zuy** [comment]
jQuery ? ES 6 это версия JavaScript

**Comment by ghost** [comment]
Код, который ты скинул - это ведь JavaScript, который использует библиотеку jquery?

**Comment by alex-zuy** [comment]
Обрати внимание на строковые литералы, например на селектор jQuery. Он заключен не в одинарные кавычки, а в апострофы и содержит подстановку переменных ${...}. Это string templates из ES 6

**Comment by ghost** [comment]
А зачем ты его используешь?

**Comment by alex-zuy** [comment]
Я его не использую. Это я у вас в проекте нашел и говорю ...

**Comment by ghost** [comment]
о_О

**Comment by ghost** [comment]
thx for notice, Alex

**Comment by alex-zuy** [comment]
возможно заинтересует следующий проект:
https://github.com/babel/babel/
